# Generated by Django 5.2.7 on 2025-10-28 12:33

from django.db import migrations, models

import users.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="birthday",
            field=models.DateField(
                blank=True, null=True, validators=[users.utils.validators.YearRangeValidator(1925, -10)]
            ),
        ),
    ]
